INSERT INTO works values (1, 'work1');
INSERT INTO works values (2, 'work2');

INSERT INTO users values('mkim', '112233');


INSERT INTO JOBS (code, name) VALUES ('1110', '의회 의원∙고위 공무원 및 공공단체 임원');
INSERT INTO JOBS (code, name) VALUES ('1120', '기업 고위 임원');
INSERT INTO JOBS (code, name) VALUES ('1211', '정부행정 관리자');
INSERT INTO JOBS (code, name) VALUES ('1212', '경영 지원 관리자');
INSERT INTO JOBS (code, name) VALUES ('1220', '마케팅 및 광고∙홍보 관리자');
INSERT INTO JOBS (code, name) VALUES ('1311', '연구 관리자');
INSERT INTO JOBS (code, name) VALUES ('1312', '교육 관리자');
INSERT INTO JOBS (code, name) VALUES ('1313', '법률∙경찰∙소방 및 교도 관리자');
INSERT INTO JOBS (code, name) VALUES ('1320', '보험 및 금융 관리자');
INSERT INTO JOBS (code, name) VALUES ('1331', '보건 의료 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1332', '사회복지 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1340', '문화∙예술 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1350', '정보 통신 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1390', '기타 전문 서비스 관리자');
INSERT INTO JOBS (code, name) VALUES ('1411', '건설 및 광업 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1412', '전기∙가스 및 수도 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1413', '제품 생산 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1490', '기타 건설∙전기 및 생산 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1511', '영업 및 판매 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1512', '운송 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1521', '숙박∙여행∙오락 및 스포츠 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1522', '음식 서비스 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1530', '환경∙청소 및 경비 관련 관리자');
INSERT INTO JOBS (code, name) VALUES ('1590', '기타 판매 및 고객 서비스 관리자');
INSERT INTO JOBS (code, name) VALUES ('2111', '생명과학 연구원');
INSERT INTO JOBS (code, name) VALUES ('2112', '자연과학 연구원');
INSERT INTO JOBS (code, name) VALUES ('2121', '인문과학 연구원');
INSERT INTO JOBS (code, name) VALUES ('2122', '사회과학 연구원');
INSERT INTO JOBS (code, name) VALUES ('2131', '생명과학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2132', '농림∙어업 관련 시험원');
INSERT INTO JOBS (code, name) VALUES ('2133', '자연과학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2211', '컴퓨터 하드웨어 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2212', '통신공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2221', '컴퓨터 시스템 전문가');
INSERT INTO JOBS (code, name) VALUES ('2222', '시스템 소프트웨어 개발자');
INSERT INTO JOBS (code, name) VALUES ('2223', '응용 소프트웨어 개발자');
INSERT INTO JOBS (code, name) VALUES ('2224', '웹 개발자');
INSERT INTO JOBS (code, name) VALUES ('2229', '기타 컴퓨터 시스템 및 소프트웨어 전문가');
INSERT INTO JOBS (code, name) VALUES ('2231', '데이터 전문가');
INSERT INTO JOBS (code, name) VALUES ('2232', '네트워크 시스템 개발자');
INSERT INTO JOBS (code, name) VALUES ('2233', '정보 보안 전문가');
INSERT INTO JOBS (code, name) VALUES ('2239', '기타 데이터 및 네트워크 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2241', '정보 시스템 운영자');
INSERT INTO JOBS (code, name) VALUES ('2242', '웹 운영자');
INSERT INTO JOBS (code, name) VALUES ('2250', '통신 및 방송 송출 장비 기사');
INSERT INTO JOBS (code, name) VALUES ('2311', '건축가');
INSERT INTO JOBS (code, name) VALUES ('2312', '건축공학 기술자');
INSERT INTO JOBS (code, name) VALUES ('2313', '토목공학 기술자');
INSERT INTO JOBS (code, name) VALUES ('2314', '조경 기술자');
INSERT INTO JOBS (code, name) VALUES ('2315', '도시 및 교통 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2316', '측량 및 지리 정보 전문가');
INSERT INTO JOBS (code, name) VALUES ('2317', '건설자재 시험원');
INSERT INTO JOBS (code, name) VALUES ('2321', '화학공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2322', '화학공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2331', '금속∙재료 공학 연구원 및 기술자');
INSERT INTO JOBS (code, name) VALUES ('2332', '금속 및 재료 공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2341', '전기공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2342', '전자공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2343', '전기 및 전자공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2351', '기계공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2352', '로봇공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2353', '기계 및 로봇공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2361', '방재 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2362', '소방공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2363', '소방공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2364', '산업 안전 및 위험 관리원');
INSERT INTO JOBS (code, name) VALUES ('2365', '보건 위생 및 환경 검사원');
INSERT INTO JOBS (code, name) VALUES ('2366', '비파괴 검사원');
INSERT INTO JOBS (code, name) VALUES ('2371', '환경공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2372', '가스∙에너지 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2373', '환경공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2374', '가스 및 에너지 시험원');
INSERT INTO JOBS (code, name) VALUES ('2381', '항공기 조종사');
INSERT INTO JOBS (code, name) VALUES ('2382', '선장∙항해사 및 도선사');
INSERT INTO JOBS (code, name) VALUES ('2383', '관제사');
INSERT INTO JOBS (code, name) VALUES ('2391', '식품공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2392', '섬유공학 기술자 및 연구원');
INSERT INTO JOBS (code, name) VALUES ('2393', '식품공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2394', '섬유공학 시험원');
INSERT INTO JOBS (code, name) VALUES ('2395', '제도사');
INSERT INTO JOBS (code, name) VALUES ('2399', '기타 공학 관련 기술자 및 시험원');
INSERT INTO JOBS (code, name) VALUES ('2411', '전문 의사');
INSERT INTO JOBS (code, name) VALUES ('2412', '일반 의사');
INSERT INTO JOBS (code, name) VALUES ('2413', '한의사');
INSERT INTO JOBS (code, name) VALUES ('2414', '치과 의사');
INSERT INTO JOBS (code, name) VALUES ('2415', '수의사');
INSERT INTO JOBS (code, name) VALUES ('2420', '약사 및 한약사');
INSERT INTO JOBS (code, name) VALUES ('2430', '간호사');
INSERT INTO JOBS (code, name) VALUES ('2440', '영양사');
INSERT INTO JOBS (code, name) VALUES ('2451', '임상병리사');
INSERT INTO JOBS (code, name) VALUES ('2452', '방사선사');
INSERT INTO JOBS (code, name) VALUES ('2453', '치과기공사');
INSERT INTO JOBS (code, name) VALUES ('2454', '치과위생사');
INSERT INTO JOBS (code, name) VALUES ('2455', '재활공학 기사');
INSERT INTO JOBS (code, name) VALUES ('2456', '물리 및 작업 치료사');
INSERT INTO JOBS (code, name) VALUES ('2457', '임상심리사');
INSERT INTO JOBS (code, name) VALUES ('2459', '기타 치료∙재활사 및 의료기사');
INSERT INTO JOBS (code, name) VALUES ('2461', '응급 구조사');
INSERT INTO JOBS (code, name) VALUES ('2462', '위생사');
INSERT INTO JOBS (code, name) VALUES ('2463', '안경사');
INSERT INTO JOBS (code, name) VALUES ('2464', '의무 기록사');
INSERT INTO JOBS (code, name) VALUES ('2465', '간호조무사');
INSERT INTO JOBS (code, name) VALUES ('2466', '안마사');
INSERT INTO JOBS (code, name) VALUES ('2471', '사회복지사');
INSERT INTO JOBS (code, name) VALUES ('2472', '보육교사');
INSERT INTO JOBS (code, name) VALUES ('2473', '직업상담사');
INSERT INTO JOBS (code, name) VALUES ('2474', '상담 전문가');
INSERT INTO JOBS (code, name) VALUES ('2475', '청소년 지도사');
INSERT INTO JOBS (code, name) VALUES ('2476', '시민 단체 활동가');
INSERT INTO JOBS (code, name) VALUES ('2479', '기타 사회복지 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('2481', '성직자');
INSERT INTO JOBS (code, name) VALUES ('2489', '기타 종교 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('2511', '대학교수');
INSERT INTO JOBS (code, name) VALUES ('2512', '대학 시간강사');
INSERT INTO JOBS (code, name) VALUES ('2521', '중∙고등학교 교사');
INSERT INTO JOBS (code, name) VALUES ('2522', '초등학교 교사');
INSERT INTO JOBS (code, name) VALUES ('2523', '특수교육 교사');
INSERT INTO JOBS (code, name) VALUES ('2530', '유치원 교사');
INSERT INTO JOBS (code, name) VALUES ('2541', '문리 및 어학 강사');
INSERT INTO JOBS (code, name) VALUES ('2542', '컴퓨터 강사');
INSERT INTO JOBS (code, name) VALUES ('2543', '기술 및 기능계 강사');
INSERT INTO JOBS (code, name) VALUES ('2544', '예능 강사');
INSERT INTO JOBS (code, name) VALUES ('2545', '학습지 및 교육 교구 방문강사');
INSERT INTO JOBS (code, name) VALUES ('2549', '기타 문리∙기술 및 예능 강사');
INSERT INTO JOBS (code, name) VALUES ('2591', '장학관∙연구관 및 교육 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2592', '대학 교육 조교');
INSERT INTO JOBS (code, name) VALUES ('2599', '기타 교사');
INSERT INTO JOBS (code, name) VALUES ('2611', '판사 및 검사');
INSERT INTO JOBS (code, name) VALUES ('2612', '변호사');
INSERT INTO JOBS (code, name) VALUES ('2613', '법무사 및 집행관');
INSERT INTO JOBS (code, name) VALUES ('2614', '변리사');
INSERT INTO JOBS (code, name) VALUES ('2619', '기타 법률 전문가');
INSERT INTO JOBS (code, name) VALUES ('2620', '정부 및 공공 행정 전문가');
INSERT INTO JOBS (code, name) VALUES ('2711', '인사 및 노사 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2712', '회계사');
INSERT INTO JOBS (code, name) VALUES ('2713', '세무사');
INSERT INTO JOBS (code, name) VALUES ('2714', '관세사');
INSERT INTO JOBS (code, name) VALUES ('2715', '경영 및 진단 전문가');
INSERT INTO JOBS (code, name) VALUES ('2721', '투자 및 신용 분석가');
INSERT INTO JOBS (code, name) VALUES ('2722', '자산 운용가');
INSERT INTO JOBS (code, name) VALUES ('2723', '보험 및 금융 상품 개발자');
INSERT INTO JOBS (code, name) VALUES ('2724', '증권 및 외환 딜러');
INSERT INTO JOBS (code, name) VALUES ('2725', '손해 사정사');
INSERT INTO JOBS (code, name) VALUES ('2729', '기타 금융 및 보험 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2731', '상품 기획 전문가');
INSERT INTO JOBS (code, name) VALUES ('2732', '여행 상품 개발자');
INSERT INTO JOBS (code, name) VALUES ('2733', '광고 및 홍보 전문가');
INSERT INTO JOBS (code, name) VALUES ('2734', '조사 전문가');
INSERT INTO JOBS (code, name) VALUES ('2735', '행사 기획자');
INSERT INTO JOBS (code, name) VALUES ('2741', '감정 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2742', '해외 영업원');
INSERT INTO JOBS (code, name) VALUES ('2743', '기술 영업원');
INSERT INTO JOBS (code, name) VALUES ('2744', '상품 중개인 및 경매사');
INSERT INTO JOBS (code, name) VALUES ('2745', '부동산 컨설턴트 및 중개사');
INSERT INTO JOBS (code, name) VALUES ('2749', '기타 기술 영업 및 중개 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('2811', '작가');
INSERT INTO JOBS (code, name) VALUES ('2812', '출판물 전문가');
INSERT INTO JOBS (code, name) VALUES ('2813', '기자 및 언론 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2814', '번역가 및 통역가');
INSERT INTO JOBS (code, name) VALUES ('2821', '학예사 및 문화재 보존원');
INSERT INTO JOBS (code, name) VALUES ('2822', '사서 및 기록물 관리사');
INSERT INTO JOBS (code, name) VALUES ('2831', '감독 및 기술 감독');
INSERT INTO JOBS (code, name) VALUES ('2832', '배우 및 모델');
INSERT INTO JOBS (code, name) VALUES ('2833', '아나운서 및 리포터');
INSERT INTO JOBS (code, name) VALUES ('2834', '촬영기사');
INSERT INTO JOBS (code, name) VALUES ('2835', '음향 및 녹음 기사');
INSERT INTO JOBS (code, name) VALUES ('2836', '영상∙녹화 및 편집 기사');
INSERT INTO JOBS (code, name) VALUES ('2837', '조명기사 및 영사기사');
INSERT INTO JOBS (code, name) VALUES ('2839', '기타 연극∙영화 및 영상 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('2841', '화가 및 조각가');
INSERT INTO JOBS (code, name) VALUES ('2842', '사진기자 및 사진가');
INSERT INTO JOBS (code, name) VALUES ('2843', '만화가 및 만화영화 작가');
INSERT INTO JOBS (code, name) VALUES ('2844', '국악 및 전통 예능인');
INSERT INTO JOBS (code, name) VALUES ('2845', '지휘자∙작곡가 및 연주가');
INSERT INTO JOBS (code, name) VALUES ('2846', '가수 및 성악가');
INSERT INTO JOBS (code, name) VALUES ('2847', '무용가 및 안무가');
INSERT INTO JOBS (code, name) VALUES ('2849', '기타 시각 및 공연 예술가');
INSERT INTO JOBS (code, name) VALUES ('2851', '제품 디자이너');
INSERT INTO JOBS (code, name) VALUES ('2852', '패션 디자이너');
INSERT INTO JOBS (code, name) VALUES ('2853', '실내장식 디자이너');
INSERT INTO JOBS (code, name) VALUES ('2854', '시각 디자이너');
INSERT INTO JOBS (code, name) VALUES ('2855', '미디어 콘텐츠 디자이너');
INSERT INTO JOBS (code, name) VALUES ('2861', '스포츠 감독 및 코치');
INSERT INTO JOBS (code, name) VALUES ('2862', '직업 운동선수');
INSERT INTO JOBS (code, name) VALUES ('2863', '경기 심판 및 경기 기록원');
INSERT INTO JOBS (code, name) VALUES ('2869', '기타 스포츠 및 레크리에이션 관련 전문가');
INSERT INTO JOBS (code, name) VALUES ('2870', '주방장 및 요리 연구가');
INSERT INTO JOBS (code, name) VALUES ('2881', '공연·영화 및 음반 기획자');
INSERT INTO JOBS (code, name) VALUES ('2882', '연예인 및 스포츠 매니저');
INSERT INTO JOBS (code, name) VALUES ('3111', '조세행정 사무원');
INSERT INTO JOBS (code, name) VALUES ('3112', '관세행정 사무원');
INSERT INTO JOBS (code, name) VALUES ('3113', '병무행정 사무원');
INSERT INTO JOBS (code, name) VALUES ('3114', '국가 및 지방 행정 사무원');
INSERT INTO JOBS (code, name) VALUES ('3115', '공공행정 사무원');
INSERT INTO JOBS (code, name) VALUES ('3121', '기획 및 마케팅 사무원');
INSERT INTO JOBS (code, name) VALUES ('3122', '인사 및 교육∙훈련 사무원');
INSERT INTO JOBS (code, name) VALUES ('3123', '자재 관리 사무원');
INSERT INTO JOBS (code, name) VALUES ('3124', '생산 및 품질 관리 사무원');
INSERT INTO JOBS (code, name) VALUES ('3125', '무역 사무원');
INSERT INTO JOBS (code, name) VALUES ('3126', '운송 사무원');
INSERT INTO JOBS (code, name) VALUES ('3127', '총무 사무원 및 대학 행정조교');
INSERT INTO JOBS (code, name) VALUES ('3131', '회계 사무원');
INSERT INTO JOBS (code, name) VALUES ('3132', '경리 사무원');
INSERT INTO JOBS (code, name) VALUES ('3141', '비서');
INSERT INTO JOBS (code, name) VALUES ('3142', '전산 자료 입력원 및 사무 보조원');
INSERT INTO JOBS (code, name) VALUES ('3201', '출납 창구 사무원');
INSERT INTO JOBS (code, name) VALUES ('3202', '보험 심사원 및 사무원');
INSERT INTO JOBS (code, name) VALUES ('3203', '은행 사무원');
INSERT INTO JOBS (code, name) VALUES ('3204', '증권 사무원');
INSERT INTO JOBS (code, name) VALUES ('3205', '수금원 및 신용 추심원');
INSERT INTO JOBS (code, name) VALUES ('3209', '기타 금융 사무원');
INSERT INTO JOBS (code, name) VALUES ('3301', '법률 관련 사무원');
INSERT INTO JOBS (code, name) VALUES ('3302', '감사 사무원');
INSERT INTO JOBS (code, name) VALUES ('3910', '통계 관련 사무원');
INSERT INTO JOBS (code, name) VALUES ('3921', '여행 사무원');
INSERT INTO JOBS (code, name) VALUES ('3922', '안내∙접수원 및 전화교환원');
INSERT INTO JOBS (code, name) VALUES ('3991', '고객 상담 및 모니터 요원');
INSERT INTO JOBS (code, name) VALUES ('3999', '기타 사무원');
INSERT INTO JOBS (code, name) VALUES ('4111', '경찰관 및 수사관');
INSERT INTO JOBS (code, name) VALUES ('4112', '소방관');
INSERT INTO JOBS (code, name) VALUES ('4113', '소년원 학교 교사 및 교도관');
INSERT INTO JOBS (code, name) VALUES ('4121', '경호원');
INSERT INTO JOBS (code, name) VALUES ('4122', '청원경찰');
INSERT INTO JOBS (code, name) VALUES ('4123', '시설 및 특수 경비원');
INSERT INTO JOBS (code, name) VALUES ('4129', '기타 경호 및 보안 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('4211', '돌봄 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4212', '보육 및 교사 보조 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4219', '기타 돌봄 및 보건 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4221', '이용사');
INSERT INTO JOBS (code, name) VALUES ('4222', '미용사');
INSERT INTO JOBS (code, name) VALUES ('4223', '피부 및 체형 관리사');
INSERT INTO JOBS (code, name) VALUES ('4224', '메이크업 아티스트 및 분장사');
INSERT INTO JOBS (code, name) VALUES ('4229', '기타 미용 관련 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4231', '결혼상담원 및 웨딩플래너');
INSERT INTO JOBS (code, name) VALUES ('4232', '혼례 종사원');
INSERT INTO JOBS (code, name) VALUES ('4233', '장례 상담원 및 장례 지도사');
INSERT INTO JOBS (code, name) VALUES ('4291', '반려동물 미용 및 관리 종사원');
INSERT INTO JOBS (code, name) VALUES ('4292', '점술가 및 민속신앙 종사원');
INSERT INTO JOBS (code, name) VALUES ('4293', '개인 생활 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4311', '항공기 객실 승무원');
INSERT INTO JOBS (code, name) VALUES ('4312', '선박 및 열차 객실 승무원');
INSERT INTO JOBS (code, name) VALUES ('4321', '여가 및 관광 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4322', '숙박시설 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4323', '오락시설 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4329', '기타 여가 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('4411', '한식 조리사');
INSERT INTO JOBS (code, name) VALUES ('4412', '중식 조리사');
INSERT INTO JOBS (code, name) VALUES ('4413', '양식 조리사');
INSERT INTO JOBS (code, name) VALUES ('4414', '일식 조리사');
INSERT INTO JOBS (code, name) VALUES ('4415', '음료 조리사');
INSERT INTO JOBS (code, name) VALUES ('4419', '기타 조리사');
INSERT INTO JOBS (code, name) VALUES ('4421', '바텐더');
INSERT INTO JOBS (code, name) VALUES ('4422', '웨이터');
INSERT INTO JOBS (code, name) VALUES ('4429', '기타 음식 서비스 종사원');
INSERT INTO JOBS (code, name) VALUES ('5101', '자동차 영업원');
INSERT INTO JOBS (code, name) VALUES ('5102', '제품 및 광고 영업원');
INSERT INTO JOBS (code, name) VALUES ('5103', '보험 모집인 및 투자 권유 대행인');
INSERT INTO JOBS (code, name) VALUES ('5104', '대출 및 신용카드 모집인');
INSERT INTO JOBS (code, name) VALUES ('5211', '소규모 상점 경영 및 일선 관리 종사원');
INSERT INTO JOBS (code, name) VALUES ('5212', '상점 판매원');
INSERT INTO JOBS (code, name) VALUES ('5213', '매표원 및 복권 판매원');
INSERT INTO JOBS (code, name) VALUES ('5214', '매장 계산원 및 요금 정산원');
INSERT INTO JOBS (code, name) VALUES ('5220', '상품 대여원');
INSERT INTO JOBS (code, name) VALUES ('5311', '단말기 및 통신 서비스 판매원');
INSERT INTO JOBS (code, name) VALUES ('5312', '온라인 쇼핑 판매원');
INSERT INTO JOBS (code, name) VALUES ('5313', '텔레마케터');
INSERT INTO JOBS (code, name) VALUES ('5321', '방문 판매원');
INSERT INTO JOBS (code, name) VALUES ('5322', '노점 및 이동 판매원');
INSERT INTO JOBS (code, name) VALUES ('5323', '홍보 도우미 및 판촉원');
INSERT INTO JOBS (code, name) VALUES ('6111', '곡식작물 재배원');
INSERT INTO JOBS (code, name) VALUES ('6112', '채소 및 특용작물 재배원');
INSERT INTO JOBS (code, name) VALUES ('6113', '과수작물 재배원');
INSERT INTO JOBS (code, name) VALUES ('6121', '원예작물 재배원');
INSERT INTO JOBS (code, name) VALUES ('6122', '조경원');
INSERT INTO JOBS (code, name) VALUES ('6131', '낙농업 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('6132', '가축 사육 종사원');
INSERT INTO JOBS (code, name) VALUES ('6139', '기타 사육 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('6201', '조림∙산림경영인 및 벌목원');
INSERT INTO JOBS (code, name) VALUES ('6209', '임산물 채취 및 기타 임업 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('6301', '양식원');
INSERT INTO JOBS (code, name) VALUES ('6302', '어부 및 해녀');
INSERT INTO JOBS (code, name) VALUES ('7101', '제빵사 및 제과원');
INSERT INTO JOBS (code, name) VALUES ('7102', '떡 제조원');
INSERT INTO JOBS (code, name) VALUES ('7103', '정육가공원 및 도축원');
INSERT INTO JOBS (code, name) VALUES ('7104', '식품 및 담배 등급원');
INSERT INTO JOBS (code, name) VALUES ('7105', '김치 및 밑반찬 제조 종사원');
INSERT INTO JOBS (code, name) VALUES ('7109', '기타 식품가공 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('7211', '패턴사');
INSERT INTO JOBS (code, name) VALUES ('7212', '재단사');
INSERT INTO JOBS (code, name) VALUES ('7213', '재봉사');
INSERT INTO JOBS (code, name) VALUES ('7214', '제화원');
INSERT INTO JOBS (code, name) VALUES ('7219', '기타 섬유 및 가죽 관련 기능 종사원');
INSERT INTO JOBS (code, name) VALUES ('7221', '한복 제조원');
INSERT INTO JOBS (code, name) VALUES ('7222', '양장 및 양복 제조원');
INSERT INTO JOBS (code, name) VALUES ('7223', '모피 및 가죽 의복 제조원');
INSERT INTO JOBS (code, name) VALUES ('7224', '의복∙가죽 및 모피 수선원');
INSERT INTO JOBS (code, name) VALUES ('7229', '기타 의복 제조 관련 기능 종사원');
INSERT INTO JOBS (code, name) VALUES ('7301', '목제품 제조 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('7302', '가구 제조 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7303', '악기 제조 및 조율사');
INSERT INTO JOBS (code, name) VALUES ('7304', '간판 제작 및 설치원');
INSERT INTO JOBS (code, name) VALUES ('7411', '금형원');
INSERT INTO JOBS (code, name) VALUES ('7412', '주조원');
INSERT INTO JOBS (code, name) VALUES ('7413', '단조원');
INSERT INTO JOBS (code, name) VALUES ('7421', '제관원');
INSERT INTO JOBS (code, name) VALUES ('7422', '판금원');
INSERT INTO JOBS (code, name) VALUES ('7430', '용접원');
INSERT INTO JOBS (code, name) VALUES ('7510', '자동차 정비원');
INSERT INTO JOBS (code, name) VALUES ('7521', '항공기 정비원');
INSERT INTO JOBS (code, name) VALUES ('7522', '선박 정비원');
INSERT INTO JOBS (code, name) VALUES ('7523', '철도 기관차 및 전동차 정비원');
INSERT INTO JOBS (code, name) VALUES ('7529', '기타 운송장비 정비원');
INSERT INTO JOBS (code, name) VALUES ('7531', '공업기계 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7532', '승강기 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7533', '물품 이동 장비 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7534', '냉동∙냉장∙공조기 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7535', '보일러 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7536', '건설∙광업기계 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7539', '농업용∙기타 기계장비 설치 및 정비원');
INSERT INTO JOBS (code, name) VALUES ('7611', '사무용 전자기기 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7612', '가전제품 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7619', '기타 전기∙전자기기 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7621', '산업 전기공');
INSERT INTO JOBS (code, name) VALUES ('7622', '내선 전기공');
INSERT INTO JOBS (code, name) VALUES ('7623', '외선 전기공');
INSERT INTO JOBS (code, name) VALUES ('7711', '컴퓨터 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7712', '이동전화기 수리원');
INSERT INTO JOBS (code, name) VALUES ('7719', '기타 정보 통신기기 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7721', '방송 관련 장비 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7722', '통신 관련 장비 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7723', '통신·방송∙인터넷케이블 설치 및 수리원');
INSERT INTO JOBS (code, name) VALUES ('7811', '강구조물 가공원 및 건립원');
INSERT INTO JOBS (code, name) VALUES ('7812', '경량 철골공');
INSERT INTO JOBS (code, name) VALUES ('7821', '철근공');
INSERT INTO JOBS (code, name) VALUES ('7822', '콘크리트공');
INSERT INTO JOBS (code, name) VALUES ('7823', '건축 석공');
INSERT INTO JOBS (code, name) VALUES ('7824', '건축 목공');
INSERT INTO JOBS (code, name) VALUES ('7825', '조적공 및 석재 부설원');
INSERT INTO JOBS (code, name) VALUES ('7829', '기타 건설 관련 기능 종사원');
INSERT INTO JOBS (code, name) VALUES ('7831', '미장공');
INSERT INTO JOBS (code, name) VALUES ('7832', '방수공');
INSERT INTO JOBS (code, name) VALUES ('7833', '단열공');
INSERT INTO JOBS (code, name) VALUES ('7834', '바닥재 시공원');
INSERT INTO JOBS (code, name) VALUES ('7835', '도배공 및 유리 부착원');
INSERT INTO JOBS (code, name) VALUES ('7836', '건축 도장공');
INSERT INTO JOBS (code, name) VALUES ('7837', '새시 조립 및 설치원');
INSERT INTO JOBS (code, name) VALUES ('7839', '기타 건축 마감 관련 기능 종사원');
INSERT INTO JOBS (code, name) VALUES ('7841', '광원∙채석원 및 석재 절단원');
INSERT INTO JOBS (code, name) VALUES ('7842', '철로 설치 및 보수원');
INSERT INTO JOBS (code, name) VALUES ('7849', '기타 채굴 및 토목 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('7911', '공예원');
INSERT INTO JOBS (code, name) VALUES ('7912', '귀금속 및 보석 세공원');
INSERT INTO JOBS (code, name) VALUES ('7921', '건설 배관공');
INSERT INTO JOBS (code, name) VALUES ('7922', '공업 배관공');
INSERT INTO JOBS (code, name) VALUES ('7929', '기타 배관공');
INSERT INTO JOBS (code, name) VALUES ('7991', '배관 세정원 및 방역원');
INSERT INTO JOBS (code, name) VALUES ('7999', '기타 기능 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('8111', '제분 및 도정 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8112', '곡물가공 제품 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8113', '육류∙어패류 및 낙농품 가공 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8114', '과실 및 채소 가공 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8120', '음료 제조 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8190', '기타 식품가공 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8211', '섬유 제조 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8212', '표백 및 염색 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8221', '직조기 및 편직기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8222', '신발 제조기 조작원 및 조립원');
INSERT INTO JOBS (code, name) VALUES ('8229', '기타 직물∙신발 관련 기계 조작원 및 조립원');
INSERT INTO JOBS (code, name) VALUES ('8230', '세탁 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8311', '석유 및 천연가스 제조 관련 제어 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8312', '화학물 가공 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8319', '기타 석유 및 화학물 가공 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8321', '화학제품 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8322', '타이어 및 고무제품 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8323', '플라스틱제품 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8324', '고무 및 플라스틱제품 조립원');
INSERT INTO JOBS (code, name) VALUES ('8411', '주조기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8412', '단조기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8413', '용접기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8414', '금속가공 관련 제어 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8415', '금속가공 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8416', '제관기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8417', '판금기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8421', '도장기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8422', '도금 및 금속 분무기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8431', '유리 제조 및 가공기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8432', '점토제품 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8433', '시멘트 및 광물제품 제조기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8434', '광석 및 석제품 가공기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8439', '기타 비금속제품 관련 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8510', '금속 공작 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8520', '냉난방 관련 설비 조작원');
INSERT INTO JOBS (code, name) VALUES ('8530', '자동 조립라인 및 산업용로봇 조작원');
INSERT INTO JOBS (code, name) VALUES ('8541', '자동차 조립원');
INSERT INTO JOBS (code, name) VALUES ('8542', '자동차 부품 조립원');
INSERT INTO JOBS (code, name) VALUES ('8543', '운송장비 조립원');
INSERT INTO JOBS (code, name) VALUES ('8544', '일반기계 조립원');
INSERT INTO JOBS (code, name) VALUES ('8550', '금속기계 부품 조립원');
INSERT INTO JOBS (code, name) VALUES ('8610', '발전 및 배전장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8620', '전기 및 전자설비 조작원');
INSERT INTO JOBS (code, name) VALUES ('8631', '전기 부품 및 제품 제조 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8632', '전자 부품 및 제품 제조 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8640', '전기∙전자 부품 및 제품 조립원');
INSERT INTO JOBS (code, name) VALUES ('8710', '철도 및 전동차 기관사');
INSERT INTO JOBS (code, name) VALUES ('8720', '철도운송 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('8731', '택시 운전원');
INSERT INTO JOBS (code, name) VALUES ('8732', '버스 운전원');
INSERT INTO JOBS (code, name) VALUES ('8733', '화물차 및 특수차 운전원');
INSERT INTO JOBS (code, name) VALUES ('8739', '기타 자동차 운전원');
INSERT INTO JOBS (code, name) VALUES ('8740', '물품 이동 장비 조작원');
INSERT INTO JOBS (code, name) VALUES ('8750', '건설 및 채굴기계 운전원');
INSERT INTO JOBS (code, name) VALUES ('8760', '선박 승무원 및 관련 종사원');
INSERT INTO JOBS (code, name) VALUES ('8810', '상하수도 처리 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8820', '재활용 처리 및 소각로 조작원');
INSERT INTO JOBS (code, name) VALUES ('8911', '목재가공 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8912', '가구 조립원');
INSERT INTO JOBS (code, name) VALUES ('8913', '펄프 및 종이 제조 장치 조작원');
INSERT INTO JOBS (code, name) VALUES ('8914', '종이제품 생산기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8919', '기타 목재 및 종이 관련 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('8921', '인쇄기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8922', '사진 인화 및 현상기 조작원');
INSERT INTO JOBS (code, name) VALUES ('8990', '기타 기계 조작원');
INSERT INTO JOBS (code, name) VALUES ('9100', '건설 및 광업 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('9210', '하역 및 적재 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('9221', '우편집배원');
INSERT INTO JOBS (code, name) VALUES ('9222', '택배원');
INSERT INTO JOBS (code, name) VALUES ('9223', '음식 배달원');
INSERT INTO JOBS (code, name) VALUES ('9229', '기타 배달원');
INSERT INTO JOBS (code, name) VALUES ('9300', '제조 관련 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('9411', '청소원');
INSERT INTO JOBS (code, name) VALUES ('9412', '환경미화원 및 재활용품 수거원');
INSERT INTO JOBS (code, name) VALUES ('9421', '건물 관리원');
INSERT INTO JOBS (code, name) VALUES ('9422', '검표원');
INSERT INTO JOBS (code, name) VALUES ('9511', '가사 도우미');
INSERT INTO JOBS (code, name) VALUES ('9512', '육아 도우미');
INSERT INTO JOBS (code, name) VALUES ('9521', '패스트푸드 준비원');
INSERT INTO JOBS (code, name) VALUES ('9522', '주방 보조원');
INSERT INTO JOBS (code, name) VALUES ('9531', '주유원');
INSERT INTO JOBS (code, name) VALUES ('9539', '기타 판매 관련 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('9910', '농림∙어업 관련 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('9921', '계기 검침원 및 가스 점검원');
INSERT INTO JOBS (code, name) VALUES ('9922', '자동판매기 관리원');
INSERT INTO JOBS (code, name) VALUES ('9923', '주차 관리원 및 안내원');
INSERT INTO JOBS (code, name) VALUES ('9991', '구두 미화원');
INSERT INTO JOBS (code, name) VALUES ('9992', '세탁원 및 다림질원');
INSERT INTO JOBS (code, name) VALUES ('9999', '기타 서비스 관련 단순 종사원');
INSERT INTO JOBS (code, name) VALUES ('A011', '영관급 이상 장교');
INSERT INTO JOBS (code, name) VALUES ('A012', '위관급 장교');
INSERT INTO JOBS (code, name) VALUES ('A020', '부사관');
INSERT INTO JOBS (code, name) VALUES ('A090', '기타 군인');
INSERT INTO JOBS (code, name) VALUES ('W111', '주부');
INSERT INTO JOBS (code, name) VALUES ('X111', '어린이집원생');
INSERT INTO JOBS (code, name) VALUES ('X112', '유치원생');
INSERT INTO JOBS (code, name) VALUES ('X113', '초등학생');
INSERT INTO JOBS (code, name) VALUES ('X114', '중학생');
INSERT INTO JOBS (code, name) VALUES ('X115', '고등학생');
INSERT INTO JOBS (code, name) VALUES ('X116', '대학생 이상');
INSERT INTO JOBS (code, name) VALUES ('Y111', '무직');
